CompassTSScanner:
  InputFileName: "rootfiles/compass/DataR_CH8@V1730B_47_runsync_3.root"
  TreeName: Data_R
  BranchName: Timestamp
#  FirstEntry: 0
#  LastEntry: 10000

IDaqLUPOTSScanner:
  InputFileName: "rootfiles/idaq/data0014.root"
  TreeName: tree
  BranchName: IDaqData
#  FirstEntry: 0
#  LastEntry: 10000

CompassTSMerger:
  OutputFileName: rootfiles/ts/IDaq_Compass_TS.root
  TreeName: TS
  BranchName: TS
  ClassName: OutputTreeData<ULong64_t, ULong64_t>
  TimeWindowLow: -1000000000
  TimeWindowUp: 1000000000
  TimeStampScale: 40
  ScanWindow: 1E+9  
  PrintFrequency: 10
  OtherBranches:
    - Channel