CompassTSScanner:
  InputFileName: "rootfiles/compass/DataR_CH8@V1730B_47_runsync_3.root"
  TreeName: Data_R
  BranchName: Timestamp
  OtherBranches:
    - Channel
#  FirstEntry: 0
#  LastEntry: 10000

IDaqLUPOTSScanner:
  InputFileName: "rootfiles/idaq/data0016.root"
  TreeName: tree
  BranchName: IDaqData
#  FirstEntry: 0
#  LastEntry: 10000

CompassTSMerger:
  OutputFileName: rootfiles/ts/IDaq_Compass_TS.root
  TreeName: TS
  BranchName: TS
  ClassName: OutputTreeData<ULong64_t, ULong64_t>
  TimeWindowLow: 10000000000 # in ns
  TimeWindowUp: 10000000000 # in ns
  TimeStampScale1: 10 # scale to ns
  #TimeStampScale2: 0.001 # scale to ns
  ScanWindow: 10 
  PrintFrequency: 10
  OtherBranches:
    - Channel

GrapeTSScanner:
  InputFileName: "rootfiles/grape_dump/run0074.root"
  TreeName: OutputTree
  BranchName: grape_dumped
#  FirstEntry: 0
#  LastEntry: 10000

IDaqMyriadTSScanner:
  InputFileName: "rootfiles/idaq/data0016.root"
  TreeName: tree
  BranchName: IDaqData
#  FirstEntry: 0
#  LastEntry: 10000

GrapeTSMerger:
  OutputFileName: rootfiles/ts/IDaq_Grape_TS.root
  TreeName: TS
  BranchName: TS
  ClassName: OutputTreeData<IDaqData, GrapeData>
  TimeWindowLow: 1000000000000
  TimeWindowUp: 1000000000000
  #TimeStampScale1: 40
  #TimeStampScale2: 40
  ScanWindow: 10  
  PrintFrequency: 10